### ISSUE TITLE
GBA crate uses inline asm for software interrupt calls

### ISSUE THREAD

**Issue by Lokathor** [bjorn3/inline_asm_catalogue#4]
https://github.com/rust-console/gba/blob/master/src/bios.rs

Basically all the calls here are mild setup of some sort and then an `swi` instruction.

I would like to use _more_ inline ASM but cannot because right now rust can't intermix thumb code and arm code and the additional code would need to be arm code (so i have an external file i linker-script into the crate lib).

**Comment by bjorn3** [comment]
Thanks! It is `crt0.s` you want to make inline, right?

**Comment by Lokathor** [comment]
Well, uh, that would be very unlikely to be inline for reasons we could get in to separately.

What I would like to be inline stable are things in the `bios.rs` file, the `swi` instructions.

I was able to make things more stable friendly in a recent iteration in another repo by making a bunch of stub functions in the assembly file and then declaring them as extern "C" functions to link in, but that's also somewhat awkward.

Ideally I'd be able to use `swi` and have it fully inlined into the calling function since the `swi` itself already has a pile of overhead as is.

**Comment by bjorn3** [comment]
Updated in a65526074f123e9681b2162c2d6c8de02f350eec.
